server:
  port: 8083
  servlet:
    context-path: /api-poc/v1    
    
spring:
  profiles:
    active: local

# H2
  h2:    
    console:
      enabled: true
      path: /h2-console     
      settings:
         web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2    
        
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.H2Dialect

  security:      
    user: 
      name: admin
      password: $2a$10$FRDQgZ83i4/E7Edw6cijIu6lRxiBv5GJu5wD8CiRWC19kYTJLMBRe
      
# Token generado para el user y password de definidos más arriba (spring.security admin/test)             
nortegas:
  poc:
    token: YWRtaW46dGVzdA==        
